/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiasuhuei321_studyforopencv_OpenCVHelper */

#ifndef _Included_com_xiasuhuei321_studyforopencv_OpenCVHelper
#define _Included_com_xiasuhuei321_studyforopencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiasuhuei321_studyforopencv_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_xiasuhuei321_studyforopencv_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_xiasuhuei321_studyforopencv_OpenCVHelper
 * Method:    blurImage
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_xiasuhuei321_studyforopencv_OpenCVHelper_blurImage
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
